# Generated by Django 5.0 on 2023-12-18 21:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('notes', models.TextField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='funds.fund')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('notes', models.TextField()),
                ('is_depricated', models.BooleanField(default=False)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='processes.process')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
