# Generated by Django 5.0 on 2023-12-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processstate',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
