# Generated by Django 5.0 on 2024-01-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_alter_process_options_alter_processstate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processstate',
            options={'ordering': ['order_position']},
        ),
        migrations.AddField(
            model_name='processstate',
            name='is_approvement_required',
            field=models.BooleanField(default=False, verbose_name='Require approvement'),
        ),
    ]
