# Generated by Django 5.0 on 2023-12-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_alter_process_notes_alter_processstate_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='is_inactive',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
