# Generated by Django 5.0 on 2023-12-29 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_process_is_inactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processstate',
            old_name='is_depricated',
            new_name='is_inactive',
        ),
        migrations.AddField(
            model_name='processstate',
            name='next_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='processes.processstate'),
        ),
    ]
