# Generated by Django 5.0 on 2023-12-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_rename_is_depricated_processstate_is_inactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstate',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
    ]
