# Generated by Django 5.0 on 2024-01-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_processstate_is_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processstate',
            name='next_state',
        ),
        migrations.AddField(
            model_name='processstate',
            name='order_position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
