# Generated by Django 5.0 on 2024-01-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_remove_processstate_next_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processstate',
            name='is_first',
        ),
    ]
