# Generated by Django 5.2.12 on 2026-04-11 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('target_id', models.UUIDField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='histories', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['target_content_type', 'target_id'], name='histories_h_target__39c214_idx')],
            },
        ),
    ]
