# Generated by Django 5.2.12 on 2026-04-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0002_alter_history_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
