# Generated by Django 5.0 on 2023-12-21 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0003_alter_attachment_notes'),
        ('funds', '0004_remove_ward_attachments_remove_ward_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.ManyToManyField(related_name='ward_attachments', to='files.attachment')),
                ('cover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='files.attachment')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='funds.fund')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
