# Generated by Django 5.0 on 2024-01-06 20:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_inactive', models.BooleanField()),
                ('cover', models.ImageField(null=True, upload_to='covers')),
                ('attachments', models.ManyToManyField(related_name='ward_attachments', to='files.attachment')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='funds.fund')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
