# Generated by Django 5.0 on 2024-01-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ward',
            options={'ordering': ['-date_created']},
        ),
    ]
