# Generated by Django 5.0 on 2023-12-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='is_closed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
