# Generated by Django 5.0 on 2023-12-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0002_ward_is_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ward',
            old_name='is_closed',
            new_name='is_inactive',
        ),
    ]
