# Generated by Django 4.2.9 on 2024-01-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0005_alter_comment_options'),
        ('wards', '0003_alter_ward_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='comments',
            field=models.ManyToManyField(related_name='commented_wards', to='commons.comment'),
        ),
    ]
