# Generated by Django 4.2.9 on 2024-02-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('wards', '0004_ward_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='comments',
            field=models.ManyToManyField(related_name='commented_wards', to='comments.comment'),
        ),
    ]
