# Generated by Django 4.2.15 on 2024-09-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0005_alter_ward_comments'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ward',
            managers=[
            ],
        ),
    ]
