# Generated by Django 4.2.10 on 2024-02-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_contributor_is_internal'),
        ('mailings', '0002_mailingrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinggroup',
            name='recipients',
            field=models.ManyToManyField(to='funds.contributor'),
        ),
        migrations.DeleteModel(
            name='MailingRecipient',
        ),
    ]
