# Generated by Django 4.2.10 on 2024-02-11 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_contributor_is_internal'),
        ('mailings', '0003_mailinggroup_recipients_delete_mailingrecipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingtemplate',
            name='group',
        ),
        migrations.AddField(
            model_name='mailingtemplate',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='funds.fund'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailingtemplate',
            name='groups',
            field=models.ManyToManyField(to='mailings.mailinggroup'),
        ),
    ]
