# Generated by Django 4.2.10 on 2024-02-12 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_remove_mailingtemplate_group_mailingtemplate_fund_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingtemplate',
            name='groups',
        ),
    ]
