# Generated by Django 4.2.10 on 2024-02-12 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mailings', '0006_alter_mailingtemplate_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingtemplate',
            name='mailing_type',
        ),
        migrations.AddField(
            model_name='mailingtemplate',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
    ]
