# Generated by Django 4.2.10 on 2024-02-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0007_remove_mailingtemplate_mailing_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingtemplate',
            name='notes',
        ),
    ]
