# Generated by Django 5.2.12 on 2026-03-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('eav', '0010_alter_attribute_id_alter_enumgroup_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ('name',), 'verbose_name': 'Attribute', 'verbose_name_plural': 'Attributes'},
        ),
        migrations.AlterField(
            model_name='attribute',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Short description', max_length=256, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='value',
            name='value_text',
            field=models.TextField(blank=True, default='', verbose_name='Value text'),
        ),
        migrations.AddConstraint(
            model_name='value',
            constraint=models.UniqueConstraint(fields=('entity_ct', 'attribute', 'entity_uuid'), name='unique_entity_uuid_per_attribute'),
        ),
        migrations.AddConstraint(
            model_name='value',
            constraint=models.UniqueConstraint(fields=('entity_ct', 'attribute', 'entity_id'), name='unique_entity_id_per_attribute'),
        ),
        migrations.AddConstraint(
            model_name='value',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entity_id__isnull', False), ('entity_uuid__isnull', True)), models.Q(('entity_id__isnull', True), ('entity_uuid__isnull', False)), _connector='OR'), name='ensure_entity_id_xor_entity_uuid'),
        ),
    ]
