# Generated by Django 5.0 on 2024-01-07 12:48

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/maksym/Documents/pet-projects/rabbits/charity/private'), upload_to='files'),
        ),
    ]
