# Generated by Django 5.0 on 2024-01-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-date_created']},
        ),
    ]
