# Generated by Django 5.0 on 2023-12-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_attachment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
