# Generated by Django 4.2.15 on 2024-09-02 10:32

import commons.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_attachment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='storage_provider',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('AZURE', 'Azure')], default='AZURE', max_length=10),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=commons.fields.FundFileField(upload_to='files'),
        ),
    ]
