# Generated by Django 4.2.15 on 2024-09-23 17:57

import commons.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_attachment_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachment',
            name='thumb',
            field=commons.fields.FundFileField(null=True, upload_to='thumbs'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='storage_provider',
            field=models.CharField(default='AZURE', max_length=10),
        ),
    ]
