# Generated by Django 4.2.15 on 2025-10-08 20:12

import commons.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_attachment_is_public_attachment_thumb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='thumb',
            field=commons.fields.FundFileField(upload_to='thumbs'),
        ),
    ]
