# Generated by Django 5.2.12 on 2026-03-31 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_alter_attachment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='storage_provider',
        ),
    ]
