# Generated by Django 4.2.9 on 2024-01-28 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0011_alter_attribute_id_alter_enumgroup_id_and_more'),
        ('customfields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='attribute',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='custom_field', to='eav.attribute'),
        ),
    ]
