# Generated by Django 4.2.9 on 2024-01-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customfields', '0003_alter_customfield_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='is_searchable',
            field=models.BooleanField(default=False),
        ),
    ]
