# Generated by Django 4.2.9 on 2024-02-03 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_contributor_cover'),
        ('customfields', '0004_customfield_is_searchable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_fields', to='funds.fund'),
        ),
    ]
