# Generated by Django 4.2.10 on 2024-02-22 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_alter_processstate_options_and_more'),
        ('customfields', '0005_alter_customfield_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='linked_process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.process'),
        ),
    ]
