# Generated by Django 4.2.15 on 2025-10-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customfields', '0006_customfield_linked_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='linked_process',
        ),
    ]
