# Generated by Django 5.0 on 2024-01-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_budget_reviewers'),
        ('funds', '0003_alter_approvement_options_alter_contribution_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='approvements',
            field=models.ManyToManyField(related_name='approved_incomes', to='funds.approvement'),
        ),
    ]
