# Generated by Django 5.0 on 2024-01-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_income_amount'),
        ('funds', '0007_alter_volunteerprofile_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='approvements',
            field=models.ManyToManyField(related_name='income_logs', to='funds.approvement'),
        ),
    ]
