# Generated by Django 5.0 on 2024-01-02 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_income_approvements'),
        ('funds', '0007_alter_volunteerprofile_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='approvements',
            field=models.ManyToManyField(related_name='budget_approvements', to='funds.approvement'),
        ),
        migrations.AlterField(
            model_name='income',
            name='approvements',
            field=models.ManyToManyField(related_name='income_approvements', to='funds.approvement'),
        ),
        migrations.AlterField(
            model_name='income',
            name='contribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='funds.contribution'),
        ),
    ]
