# Generated by Django 5.0 on 2024-01-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_budget_approvements_alter_income_approvements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='end_period_date',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='start_period_date',
        ),
        migrations.AddField(
            model_name='budget',
            name='closed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
