# Generated by Django 4.2.9 on 2024-02-05 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_contributor_cover'),
        ('budgets', '0006_alter_income_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='back_contribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.contribution'),
        ),
    ]
