# Generated by Django 4.2.9 on 2024-02-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_budget_back_contribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='back_contribution',
            new_name='payout_excess_contribution',
        ),
    ]
