# Generated by Django 5.2.12 on 2026-03-28 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0008_rename_back_contribution_budget_payout_excess_contribution'),
        ('funds', '0007_contributor_is_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='payout_excess_contribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_excess_budgets', to='funds.contribution'),
        ),
    ]
