# Generated by Django 4.2.10 on 2024-02-12 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailings', '0008_remove_mailingtemplate_notes'),
        ('wards', '0005_alter_ward_comments'),
        ('funds', '0007_contributor_is_internal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SENT', ''), ('IN_PROGRESS', 'In progress'), ('PARTIALLY_SENT', 'Partially sent')], max_length=16)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funds.fund')),
                ('mailing_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailings.mailinggroup')),
                ('mailing_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailings.mailingtemplate')),
                ('wards', models.ManyToManyField(to='wards.ward')),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
    ]
