# Generated by Django 4.2.10 on 2024-02-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='name',
            field=models.CharField(max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('IN_PROGRESS', 'In progress'), ('PARTIALLY_SENT', 'Partially sent')], max_length=16),
        ),
    ]
