# Generated by Django 4.2.10 on 2024-02-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_is_draft_submission_name_submission_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Is draft'), ('SENT', 'Sent'), ('IN_PROGRESS', 'In progress'), ('PARTIALLY_SENT', 'Partially sent')], max_length=16),
        ),
    ]
