# Generated by Django 5.2.12 on 2026-03-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_remove_submission_status_submission_last_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
