# Generated by Django 5.2.12 on 2026-03-31 17:07
import uuid

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_alter_submission_last_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionlog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='submissionlog',
            name='recipients_count',
        ),
        migrations.AddField(
            model_name='submissionlog',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='submissionlog',
            name='recipient',
            field=models.CharField(default='q', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissionlog',
            name='retries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submissionlog',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid1()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissionlog',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'In queue'), ('SENT', 'Sent'), ('IN_PROGRESS', 'In progress'), ('PARTIALLY_SENT', 'Partially sent'), ('FAILED', 'Failed')], max_length=16),
        ),
    ]
