# Generated by Django 5.2.12 on 2026-03-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_remove_submissionlog_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissionlog',
            old_name='retries',
            new_name='retries_count',
        ),
        migrations.AddField(
            model_name='submissionlog',
            name='error_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='submissionlog',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
