# Generated by Django 5.2.12 on 2026-03-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_rename_retries_submissionlog_retries_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionlog',
            name='is_delivered',
            field=models.BooleanField(null=True),
        ),
    ]
