# Generated by Django 5.2.12 on 2026-03-31 18:47

import commons.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_alter_submissionlog_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionlog',
            name='file',
            field=commons.fields.FundFileField(null=True, upload_to='emails'),
        ),
    ]
