# Generated by Django 5.2.12 on 2026-03-31 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_contributor_is_internal'),
        ('submissions', '0011_submissionlog_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionlog',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund'),
            preserve_default=False,
        ),
    ]
