# Generated by Django 5.2.12 on 2026-04-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0012_submissionlog_fund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissionlog',
            old_name='recipient',
            new_name='recipient_email',
        ),
        migrations.AddField(
            model_name='submissionlog',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='submissionlog',
            name='subject',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
