# Generated by Django 5.2.12 on 2026-04-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_rename_recipient_submissionlog_recipient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionlog',
            name='error_date',
            field=models.DateTimeField(null=True),
        ),
    ]
