# Generated by Django 4.2.9 on 2024-02-02 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customfields', '0004_customfield_is_searchable'),
        ('funds', '0006_contributor_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('operand', models.CharField(choices=[('EQ', 'Equals'), ('NOT', 'Not'), ('GT', 'Great then'), ('LT', 'Less then')], max_length=10)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customfields.customfield')),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funds.fund')),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpressionValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateTimeField(blank=True, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_int', models.BigIntegerField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='filters.expression')),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='expression',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expressions', to='filters.filter'),
        ),
    ]
