# Generated by Django 4.2.9 on 2024-02-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressionvalue',
            name='value_enum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
