# Generated by Django 4.2.9 on 2024-02-03 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_contributor_cover'),
        ('filters', '0002_expressionvalue_value_enum_alter_filter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='filters.filter'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filters', to='funds.fund'),
        ),
    ]
