# Generated by Django 5.0 on 2024-01-06 20:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
        ('processes', '0001_initial'),
        ('wards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(null=True, upload_to='covers')),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='funds.fund')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leaded_projects', to=settings.AUTH_USER_MODEL)),
                ('processes', models.ManyToManyField(related_name='projects', to='processes.process')),
                ('wards', models.ManyToManyField(related_name='projects', to='wards.ward')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
