# Generated by Django 5.0 on 2023-12-20 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_attachment_type'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.attachment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='close_project_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
