# Generated by Django 5.0 on 2023-12-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_notes'),
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='wards',
            field=models.ManyToManyField(related_name='projects', to='wards.ward'),
        ),
    ]
