# Generated by Django 5.0 on 2024-01-12 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_reviewers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='reviewers',
            field=models.ManyToManyField(related_name='reviewed_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
