# Generated by Django 5.0 on 2023-12-23 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_income_amount'),
        ('projects', '0004_alter_project_wards'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='budgets.budget'),
        ),
    ]
