# Generated by Django 5.0 on 2023-12-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='close_project_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
