# Generated by Django 5.0 on 2023-12-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_close_project_date_project_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end_date',
            new_name='closed_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
