# Generated by Django 5.0 on 2023-12-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_process_is_inactive'),
        ('projects', '0007_rename_end_date_project_closed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='processes',
            field=models.ManyToManyField(related_name='projects', to='processes.process'),
        ),
    ]
