# Generated by Django 5.0 on 2024-01-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_processes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
    ]
