# Generated by Django 5.0 on 2024-01-06 20:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('files', '0001_initial'),
        ('funds', '0001_initial'),
        ('processes', '0001_initial'),
        ('projects', '0001_initial'),
        ('wards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approvement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.approvement')),
                ('approvements', models.ManyToManyField(related_name='expense_approvements', to='funds.approvement')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='budgets.budget')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order_position', models.IntegerField()),
                ('is_high_priority', models.BooleanField()),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('is_started', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('estimated_expense_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('attachments', models.ManyToManyField(to='files.attachment')),
                ('expense', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task', to='tasks.expense')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processes.process')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='projects.project')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='wards.ward')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='tasks.comment')),
                ('tagged_interlocutors', models.ManyToManyField(related_name='tags', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='tasks.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(null=True)),
                ('approvement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.approvement')),
                ('approvements', models.ManyToManyField(related_name='approved_task_states', to='funds.approvement')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processes.processstate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.taskstate'),
        ),
        migrations.AddField(
            model_name='task',
            name='states',
            field=models.ManyToManyField(related_name='state_tasks', to='tasks.taskstate'),
        ),
    ]
