# Generated by Django 5.0 on 2024-01-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='taskstate',
            options={'ordering': ['-date_created']},
        ),
    ]
