# Generated by Django 5.0 on 2023-12-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
