# Generated by Django 5.0 on 2024-01-12 00:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_expense_approvements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
