# Generated by Django 5.0 on 2023-12-21 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_comment_notes_alter_task_notes'),
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='wards.ward'),
        ),
    ]
