# Generated by Django 5.0 on 2023-12-21 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_wards'),
        ('tasks', '0006_alter_expense_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='projects.project'),
            preserve_default=False,
        ),
    ]
