# Generated by Django 5.0 on 2023-12-21 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_expense_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='expense',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task', to='tasks.expense'),
        ),
    ]
