# Generated by Django 5.0 on 2024-01-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_expense_notes_expense_reviewer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstate',
            options={'ordering': ['date_created']},
        ),
        migrations.AddField(
            model_name='taskstate',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
