# Generated by Django 5.0 on 2024-01-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_taskstate_options_taskstate_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstate',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskstate',
            name='is_review_requested',
            field=models.BooleanField(default=False),
        ),
    ]
