# Generated by Django 5.0 on 2023-12-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_expense_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
