# Generated by Django 5.0 on 2023-12-29 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_alter_process_notes_alter_processstate_notes'),
        ('tasks', '0009_task_estimated_expense_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processes.process'),
            preserve_default=False,
        ),
    ]
