# Generated by Django 5.0 on 2024-01-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0004_comment'),
        ('tasks', '0010_taskstate_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.ManyToManyField(related_name='commented_tasks', to='commons.comment'),
        ),
        migrations.AddField(
            model_name='taskstate',
            name='comments',
            field=models.ManyToManyField(related_name='commented_task_states', to='commons.comment'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
