# Generated by Django 5.0 on 2024-01-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_alter_volunteerprofile_fund'),
        ('tasks', '0010_task_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approvements',
            field=models.ManyToManyField(related_name='expense_approvements', to='funds.approvement'),
        ),
    ]
