# Generated by Django 5.0 on 2024-01-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_expense_approvements'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='states',
            field=models.ManyToManyField(related_name='state_tasks', to='tasks.taskstate'),
        ),
    ]
