# Generated by Django 4.2.9 on 2024-01-27 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_alter_processstate_options_and_more'),
        ('tasks', '0012_taskstate_request_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='processes.process'),
        ),
    ]
