# Generated by Django 4.2.9 on 2024-02-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('tasks', '0013_alter_task_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comments',
            field=models.ManyToManyField(related_name='commented_tasks', to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='taskstate',
            name='comments',
            field=models.ManyToManyField(related_name='commented_task_states', to='comments.comment'),
        ),
    ]
