# Generated by Django 5.0 on 2024-01-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_alter_volunteerprofile_fund'),
        ('tasks', '0013_taskstate_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstate',
            name='approvements',
            field=models.ManyToManyField(related_name='approved_task_states', to='funds.approvement'),
        ),
    ]
