# Generated by Django 4.2.9 on 2024-02-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_task_actual_expense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actual_expense_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
