# Generated by Django 4.2.9 on 2024-02-05 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_contributor_is_internal'),
        ('tasks', '0016_alter_task_actual_expense_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='payout_excess_contribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.contribution'),
        ),
    ]
