# Generated by Django 4.2.9 on 2024-02-10 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_contributor_is_internal'),
        ('tasks', '0017_task_payout_excess_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='payout_excess_contribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='funds.contribution'),
        ),
    ]
