# Generated by Django 4.2.10 on 2024-03-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_attachment_options'),
        ('tasks', '0018_alter_task_payout_excess_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstate',
            name='attachments',
            field=models.ManyToManyField(to='files.attachment'),
        ),
    ]
