# Generated by Django 5.0 on 2023-12-18 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_rejected', models.BooleanField()),
                ('notes', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('notes', models.TextField()),
                ('cover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.attachment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField()),
                ('is_company', models.BooleanField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributors', to='funds.fund')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('contribution_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='funds.contributor')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='funds.fund')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('notes', models.TextField()),
                ('start_period_date', models.DateField()),
                ('end_period_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('approvement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.approvement')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='funds.fund')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='approvement',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funds.fund'),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approvement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.approvement')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='funds.budget')),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funds.contribution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('cover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.attachment')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funds.fund')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('notes', models.TextField()),
                ('attachments', models.ManyToManyField(to='files.attachment')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='funds.fund')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
