# Generated by Django 5.0 on 2023-12-19 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_attachment_type'),
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='files.attachment'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='attachments',
            field=models.ManyToManyField(related_name='ward_attachments', to='files.attachment'),
        ),
    ]
