# Generated by Django 5.0 on 2024-01-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='name',
            field=models.CharField(max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
