# Generated by Django 5.0 on 2023-12-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_ward_cover_alter_ward_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
