# Generated by Django 5.0 on 2023-12-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_alter_approvement_notes_alter_budget_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='fund',
        ),
    ]
