# Generated by Django 5.0 on 2023-12-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_remove_ward_attachments_remove_ward_cover_and_more'),
        ('projects', '0004_alter_project_wards'),
        ('tasks', '0005_alter_task_ward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
