# Generated by Django 5.0 on 2024-01-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_alter_approvement_options_requestreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
