# Generated by Django 5.0 on 2024-01-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0005_contributor_email_contributor_mobile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers'),
        ),
    ]
