# Generated by Django 5.0 on 2023-12-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0005_delete_ward'),
        ('tasks', '0006_alter_expense_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='income',
            name='approvement',
        ),
        migrations.RemoveField(
            model_name='income',
            name='author',
        ),
        migrations.RemoveField(
            model_name='income',
            name='contribution',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
