# Generated by Django 5.0 on 2024-01-02 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_remove_income_budget_remove_income_approvement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volunteers', to='funds.fund'),
        ),
    ]
