# Generated by Django 4.2.9 on 2024-02-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_contributor_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
