# Generated by Django 5.2.12 on 2026-04-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_contributor_is_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
