# Generated by Django 4.2.9 on 2024-01-31 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_created']},
        ),
    ]
