# Generated by Django 4.2.9 on 2024-02-01 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_task_comments_alter_taskstate_comments'),
        ('wards', '0005_alter_ward_comments'),
        ('commons', '0006_alter_comment_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
