# Generated by Django 4.2.9 on 2024-02-10 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('commons', '0007_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_id',
            field=models.UUIDField(null=True),
        ),
    ]
