name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11.0]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install -r charity/requirements.txt
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
    - name: Run Tests
      env:
        CELERY_BROKER_QUEUE: django-celery
        CELEREY_PERIODIC_BROKER_QUEUE: django-celery-periodic
        AZURE_STORAGE_NAME: testaccountname
        DEFAULT_STORAGE_PROVIDER: LOCAL
      run: |
       python charity/manage.py test charity
